# Generated by Django 4.2.16 on 2026-06-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('cta_text', models.CharField(default='Shop Now', max_length=100)),
                ('cta_link', models.CharField(default='#', max_length=200)),
                ('cta_secondary_text', models.CharField(blank=True, max_length=100)),
                ('cta_secondary_link', models.CharField(blank=True, max_length=200)),
                ('bg_gradient', models.CharField(default='linear-gradient(135deg,#3D0808 0%,#6B1020 100%)', max_length=200)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('accent_color', models.CharField(default='#FAE8E8', max_length=20)),
                ('tag_text', models.CharField(blank=True, max_length=100)),
                ('deco_emoji', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='📦', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('filters', models.JSONField(default=list, help_text='List of filter tag strings')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('emoji', models.CharField(default='📦', max_length=10)),
                ('price', models.PositiveIntegerField(help_text='Selling price in INR')),
                ('mrp', models.PositiveIntegerField(help_text='Maximum retail price in INR')),
                ('material', models.CharField(default='Silicone', max_length=100)),
                ('badge', models.CharField(blank=True, choices=[('', 'None'), ('best', 'Bestseller'), ('new', 'New Arrival')], default='', max_length=10)),
                ('filter_tag', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('discount', models.PositiveSmallIntegerField(default=0, help_text='Individual product discount percentage (0 = no discount)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_custom', models.BooleanField(default=False, help_text='Added via admin panel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('product', 'order')},
            },
        ),
    ]
