# Generated by Django 4.2.16 on 2026-06-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('checkouts', models.PositiveIntegerField(default=0)),
                ('unique_products_viewed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('page', models.CharField(choices=[('home', 'Home'), ('category', 'Category'), ('product', 'Product'), ('cart', 'Cart'), ('checkout', 'Checkout'), ('custom', 'Custom Order'), ('about', 'About Us'), ('search', 'Search')], max_length=20)),
                ('category_key', models.CharField(blank=True, max_length=50)),
                ('product_id', models.CharField(blank=True, max_length=60)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('referrer', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('product_id', models.CharField(db_index=True, max_length=60)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('category_key', models.CharField(blank=True, max_length=50)),
                ('time_spent_ms', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
